spring:
  datasource:
    url: jdbc:h2:mem:products
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update      
       
server:
  port: 6001 

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
eureka:
 client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
   defaultZone: http://host.docker.internal:8070/eureka/        
        
      
